#!/usr/bin/python
def __init__(self):
    # Menu Notes
    '''
    1) Global Variables should be created to define each menu with a prefix of "Menu_"
    2) The type can either be "Play" or "Menu"
    3) "Play" will generate a play command using the City and Group values in lowercase.  Do not use Spaces.  Format is <tsv_files_path>/city/group.tsv
    4) "Menu" will generate another menu.  In order for this to work you have to define a Menu variable.  Do not use Spaces.  Format is Menu_city_group
    5) If you want the button to be blank leave the all fields empty.  If you do not want the button to exist comment out or delete the entry.
    6) Button Numbers read left to right.
    '''

    # Menu_Template (Menu_city_group)
    Menu_Template = {
              1: {'name': '', 'type': '', 'city': '', 'group': ''},
              2: {'name': '', 'type': '', 'city': '', 'group': ''},
              3: {'name': '', 'type': '', 'city': '', 'group': ''},
              4: {'name': '', 'type': '', 'city': '', 'group': ''},
              5: {'name': '', 'type': '', 'city': '', 'group': ''},
              6: {'name': '', 'type': '', 'city': '', 'group': ''},
              7: {'name': '', 'type': '', 'city': '', 'group': ''},
              8: {'name': '', 'type': '', 'city': '', 'group': ''},
              9: {'name': '', 'type': '', 'city': '', 'group': ''},
              10: {'name': '', 'type': '', 'city': '', 'group': ''},
              11: {'name': '', 'type': '', 'city': '', 'group': ''},
              12: {'name': '', 'type': '', 'city': '', 'group': ''},
              13: {'name': '', 'type': '', 'city': '', 'group': ''},
              14: {'name': '', 'type': '', 'city': '', 'group': ''},
              15: {'name': '', 'type': '', 'city': '', 'group': ''},
             }

    # Menu_Favorites
    Menu_Favorites = {
               1: {'name': 'BRK - Verdugo', 'type': 'play', 'city': 'Burbank', 'group': 'Verdugo_All'},
               2: {'name': 'GLN - Verdugo', 'type': 'play', 'city': 'Glendale', 'group': 'Verdugo_All'},
               3: {'name': 'PSD - Verdugo', 'type': 'play', 'city': 'Pasdaenda', 'group': 'Verdugo_All'},
               4: {'name': 'BRK - BPD', 'type': 'play', 'city': 'Burbank', 'group': 'BPD'},
               5: {'name': 'GLN - BPD', 'type': 'play', 'city': 'Glendale', 'group': 'BPD'},
               6: {'name': 'PSD - BPD', 'type': 'play', 'city': 'Pasadena', 'group': 'BPD'},
               7: {'name': 'BRK - GPD', 'type': 'play', 'city': 'Burbank', 'group': 'GPD'},
               8: {'name': 'GLN - GPD', 'type': 'play', 'city': 'Glendale', 'group': 'GPD'},
               9: {'name': 'PSD - GPD', 'type': 'play', 'city': 'Pasadena', 'group': 'GPD'},
               10: {'name': 'BRK - ICI', 'type': 'play', 'city': 'Burbank', 'group': 'ICI'},
               11: {'name': 'GLN - ICI', 'type': 'play', 'city': 'Glendale', 'group': 'ICI'},
               12: {'name': 'PSD - ICI', 'type': 'play', 'city': 'Pasadena', 'group': 'ICI'},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_ICI_Main
    Menu_ICI_Main = {
                1: {'name': 'Burbank', 'type': 'menu', 'city': 'Burbank', 'group': 'Main'},
                2: {'name': 'Glendale', 'type': 'menu', 'city': 'Glendale', 'group': 'Main'},
                3: {'name': 'Pasadena', 'type': 'menu', 'city': 'Pasadena', 'group': 'Main'},
                4: {'name': 'SCV/SFV', 'type': 'menu', 'city': 'SCV', 'group': 'Main'},
                5: {'name': 'Montebello', 'type': 'menu', 'city': 'Montebello', 'group': 'Main'},
                6: {'name': 'Pomona', 'type': 'Menu', 'city': 'Pomona', 'group': 'Main'},
                7: {'name': 'Beverly Hills', 'type': 'menu', 'city': 'BeverlyHills', 'group': 'Main'},
                8: {'name': 'Culver City', 'type': 'menu', 'city': 'Culver', 'group': 'Main'},
                9: {'name': 'Palmdale', 'type': 'menu', 'city': 'Palmdale', 'group': 'Main'},
                10: {'name': 'Glendora', 'type': 'menu', 'city': 'Glendora', 'group': 'Main'},
                11: {'name': 'South Bay', 'type': 'menu', 'city': 'SouthBay', 'group': 'Main'},
                12: {'name': 'Santa Monica', 'type': 'menu', 'city': 'SantaMonica', 'group': 'Main'},
                13: {'name': '', 'type': '', 'city': '', 'group': ''},
                14: {'name': '', 'type': '', 'city': '', 'group': ''},
                15: {'name': '', 'type': '', 'city': '', 'group': ''},
             }

    # Menu_Home
    Menu_Home = {
               1: {'name': 'ICI System', 'type': 'menu', 'city': 'ICI', 'group': 'Main'},
               2: {'name': 'CWRIS', 'type': 'menu', 'city': 'LAC', 'group': 'CWIRS'},
               3: {'name': 'LA-RICS', 'type': 'menu', 'city': 'LAC', 'group': 'LARICS'},
               # 4: {'name': '', 'type': '', 'city': '', 'group': ''},
               5: {'name': 'Orange County', 'type': 'menu', 'city': 'OC', 'group': 'CCCS'},
               # 7: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 8: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 9: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 10: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 11: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 12: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 13: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 14: {'name': '', 'type': '', 'city': '', 'group': ''},
               # 15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }

    # Menu_Burbank_Main
    Menu_Burbank_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Burbank', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Burbank', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Burbank', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Burbank', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Burbank_Verdugo_All
    Menu_Burbank_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Burbank', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Burbank', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Burbank', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Burbank', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Burbank', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Burbank', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Burbank', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Burbank', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Burbank', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Burbank', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Glendale_Main
    Menu_Glendale_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Glendale', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Glendale', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Glendale', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Glendale', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Glendale_Verdugo_All
    Menu_Glendale_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Glendale', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Glendale', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Glendale', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Glendale', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Glendale', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Glendale', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Glendale', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Glendale', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Glendale', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Glendale', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Pasadena_Main
    Menu_Pasadena_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Pasadena', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Pasdaenda', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Pasdaenda', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Pasadena', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Pasadena_Verdugo_All
    Menu_Pasadena_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Pasadena', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Pasadena', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Pasadena', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Pasadena', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Pasadena', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Pasadena', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Pasadena', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Pasadena', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Pasadena', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Pasadena', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_LAC_CWIRS
    Menu_LAC_CWIRS = {
               1: {'name': 'Basin', 'type': 'play', 'city': 'CWRIS', 'group': 'basin'},
               2: {'name': 'East', 'type': 'play', 'city': 'CWRIS', 'group': 'east'},
               3: {'name': 'Northwest', 'type': 'play', 'city': 'CWRIS', 'group': 'northwest'},
               4: {'name': 'West', 'type': '', 'city': 'CWRIS', 'group': 'west'},
               5: {'name': 'Thousand Oaks', 'type': 'play', 'city': 'CWRIS', 'group': 'thousand_oaks'},
               6: {'name': 'Palmdale', 'type': 'play', 'city': 'CWRIS', 'group': 'palmdale'},
               7: {'name': 'Catalina', 'type': 'play', 'city': 'CWIRS', 'group': 'catalina'},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_LAC_LARICS
    Menu_LAC_LARICS = {
              1: {'name': 'Verdugo Peak', 'type': 'play', 'city': 'LARICS', 'group': 'verdugo'},
              2: {'name': 'West Covina', 'type': 'play', 'city': 'LARICS', 'group': 'westcovina'},
              3: {'name': 'Torrence', 'type': 'play', 'city': 'LARICS', 'group': 'torrence'},
              4: {'name': 'SCV/Granada', 'type': 'play', 'city': 'LARICS', 'group': 'scv_granada'},
              5: {'name': 'Palmdale', 'type': 'play', 'city': 'LARICS', 'group': 'palmdale'},
              6: {'name': 'Downtown LA', 'type': 'play', 'city': 'LARICS', 'group': 'downtownla'},
              7: {'name': 'Azusa', 'type': 'play', 'city': 'LARICS', 'group': 'azusa'},
              8: {'name': '', 'type': '', 'city': '', 'group': ''},
              9: {'name': '', 'type': '', 'city': '', 'group': ''},
              10: {'name': '', 'type': '', 'city': '', 'group': ''},
              11: {'name': '', 'type': '', 'city': '', 'group': ''},
              12: {'name': '', 'type': '', 'city': '', 'group': ''},
              13: {'name': '', 'type': '', 'city': '', 'group': ''},
              14: {'name': '', 'type': '', 'city': '', 'group': ''},
              15: {'name': '', 'type': '', 'city': '', 'group': ''},
             }

    # Menu_Template (Menu_city_group)
    Menu_OC_CCCS = {
              1: {'name': 'CountyWide', 'type': 'play', 'city': 'CCCS', 'group': 'CountyWide'},
              2: {'name': 'North', 'type': 'play', 'city': 'CCCS', 'group': 'North'},
              3: {'name': 'South', 'type': 'play', 'city': 'CCCS', 'group': 'South'},
              4: {'name': '', 'type': '', 'city': '', 'group': ''},
              5: {'name': '', 'type': '', 'city': '', 'group': ''},
              6: {'name': '', 'type': '', 'city': '', 'group': ''},
              7: {'name': '', 'type': '', 'city': '', 'group': ''},
              8: {'name': '', 'type': '', 'city': '', 'group': ''},
              9: {'name': '', 'type': '', 'city': '', 'group': ''},
              10: {'name': '', 'type': '', 'city': '', 'group': ''},
              11: {'name': '', 'type': '', 'city': '', 'group': ''},
              12: {'name': '', 'type': '', 'city': '', 'group': ''},
              13: {'name': '', 'type': '', 'city': '', 'group': ''},
              14: {'name': '', 'type': '', 'city': '', 'group': ''},
              15: {'name': '', 'type': '', 'city': '', 'group': ''},
             }

    # Menu_SCV_Main
    Menu_SCV_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'SCV', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'SCV', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'SCV', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'SCV', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_SCV_Verdugo_All
    Menu_SCV_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'SCV', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'SCV', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'SCV', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'SCV', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'SCV', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'SCV', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'SCV', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'SCV', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'SCV', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'SCV', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Montebello_Main
    Menu_Montebello_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Montebello', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Montebello', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Montebello', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Montebello', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Montebello_Verdugo_All
    Menu_Montebello_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Montebello', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Montebello', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Montebello', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Montebello', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Montebello', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Montebello', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Montebello', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Montebello', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Montebello', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Montebello', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Pomona_Main
    Menu_Pomona_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Pomona', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Pomona', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Pomona', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Pomona', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Pomona_Verdugo_All
    Menu_Pomona_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Pomona', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Pomona', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Pomona', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Pomona', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Pomona', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Pomona', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Pomona', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Pomona', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Pomona', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Pomona', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_BeverlyHills_Main
    Menu_BeverlyHills_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'BeverlyHills', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'BeverlyHills', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_BeverlyHills_Verdugo_All
    Menu_BeverlyHills_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'BeverlyHills', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'BeverlyHills', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Culver_Main
    Menu_Culver_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Culver', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Culver', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Culver', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Culver', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Culver_Verdugo_All
    Menu_Culver_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Culver', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Culver', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Culver', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Culver', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Culver', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Culver', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Culver', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Culver', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Culver', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Culver', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Palmdale_Main
    Menu_Palmdale_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Palmdale', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Palmdale', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Palmdale', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Palmdale', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Palmdale_Verdugo_All
    Menu_Palmdale_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Palmdale', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Palmdale', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Palmdale', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Palmdale', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Palmdale', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Palmdale', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Palmdale', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Palmdale', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Palmdale', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Palmdale', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Glendora_Main
    Menu_Glendora_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'Glendora', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'Glendora', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'Glendora', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'Glendora', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_Glendora_Verdugo_All
    Menu_Glendora_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'Glendora', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'Glendora', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'Glendora', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'Glendora', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'Glendora', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'Glendora', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'Glendora', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'Glendora', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'Glendora', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'Glendora', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_SouthBay_Main
    Menu_SouthBay_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'SouthBay', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'SouthBay', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'SouthBay', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'SouthBay', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_SouthBay_Verdugo_All
    Menu_SouthBay_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'SouthBay', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'SouthBay', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'SouthBay', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'SouthBay', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'SouthBay', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'SouthBay', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'SouthBay', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'SouthBay', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'SouthBay', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'SouthBay', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_SantaMonica_Main
    Menu_SantaMonica_Main = {
               1: {'name': 'Verdugo Fire', 'type': 'menu', 'city': 'SantaMonica', 'group': 'Verdugo'},
               2: {'name': 'Bubank PD', 'type': 'play', 'city': 'SantaMonica', 'group': 'Verdugo_All'},
               3: {'name': 'Glendale PD', 'type': 'play', 'city': 'SantaMonica', 'group': 'Verdugo_All'},
               4: {'name': 'ICI', 'type': 'play', 'city': 'SantaMonica', 'group': 'ICI'},
               5: {'name': '', 'type': '', 'city': '', 'group': ''},
               6: {'name': '', 'type': '', 'city': '', 'group': ''},
               7: {'name': '', 'type': '', 'city': '', 'group': ''},
               8: {'name': '', 'type': '', 'city': '', 'group': ''},
               9: {'name': '', 'type': '', 'city': '', 'group': ''},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': '', 'type': '', 'city': '', 'group': ''},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
    # Menu_SantaMonica_Verdugo_All
    Menu_SantaMonica_Verdugo = {
               1: {'name': 'Red 1', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red1'},
               2: {'name': 'Red 2', 'type': 'menu', 'city': 'SantaMonica', 'group': 'Red2'},
               3: {'name': 'Red 3', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red3'},
               4: {'name': 'Red 4', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red4'},
               5: {'name': 'Red 5', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red5'},
               6: {'name': 'Red 6', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red6'},
               7: {'name': 'Red 7', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red7'},
               8: {'name': 'Red 8', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red8'},
               9: {'name': 'Red 9', 'type': 'play', 'city': 'SantaMonica', 'group': 'Red9'},
               10: {'name': '', 'type': '', 'city': '', 'group': ''},
               11: {'name': 'All', 'type': 'play', 'city': 'SantaMonica', 'group': 'Verdugo_All'},
               12: {'name': '', 'type': '', 'city': '', 'group': ''},
               13: {'name': '', 'type': '', 'city': '', 'group': ''},
               14: {'name': '', 'type': '', 'city': '', 'group': ''},
               15: {'name': '', 'type': '', 'city': '', 'group': ''},
              }
